---
title: "Untitled"
author: "Boris M Fazio"
date: "31 de febrero de 1217"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd("D:/")
library(data.table)
library(magrittr)
```

## Ejercicio 27

En una investigación para estudiar la relación entre la propensión al consumo de alcohol por parte de adolescentes varones y variables como el control parental, regulación emocional y madurez social, se desea tomar un MASs para sólo el distrito de San Miguel. Puesto que la propensión se medirá mediante una proporción, es de interés estimar esta proporción con un margen de error no mayor a 0.07 y un nivel de confianza del 95%. Usando en lo posible el paquete survey de R.

1. Halle el tamaño de muestra requerido para este estudio. Para esto y para crear su marco muestral puede hacer uso de la página web del Ministerio de Educación (<http://escale.minedu.gob.pe/web/inicio/padron-de-iiee>), la cual contiene información de todos los colegios del país en base al censo nacional escolar del 2016.

**Resolución:** Usamos la fórmula de Hájek para estimar intervalos de confianza en una población finita:

$$\text{IC} = \left[\bar{p} - z_{1-\alpha/2}\sqrt{\frac{\bar{p}(1-\bar{p})}{n-1}}\sqrt{1-\frac{n}{N}} , \bar{p} + z_{1-\alpha/2}\sqrt{\frac{\bar{p}(1-\bar{p})}{n-1}}\sqrt{1-\frac{n}{N}} \right]$$
Tomando el error como $e = \left|p-\bar{p}\right|$, el intervalo anterior implica:

$$e = z_{1-\alpha/2}\frac{\sigma}{\sqrt{n}}\sqrt{1-\frac{n}{N}} \rightarrow n = \frac{z^2_{1-\alpha/2} \sigma^2 N}{z^2_{1-\alpha/2} \sigma^2 + e^2 N}$$

2. Tome la muestra anterior y estime en base a ella el total de alumnos matriculados el 2016 en los colegios de varones de San Miguel, así como la proporción de estudiantes que pertenecen a un colegio de gestión privada. En ambos casos obtenga el error de estimación estimado de los estimadores correspondientes.

3. ¿Cree usted que el diseño MASs empleado sea apropiado para los fines de este estudio? Indique si no fuera el caso, qué dificultades acarrea este diseño.
